### PR TITLE
link to retweeter if the link is a retweet

### PR DESCRIPTION
**Pull request by tobobo**
I switched around the link a little bit so it links to the tweet on the timeline of the person who (re)tweeted. See what you think.

### CODE REVIEW

**Comment by ashlinaronin** [comment]
Thanks man! They're going to the right pages now, but the display of the target is a bit off, because the top of the tweet is at the top of the browser window but partially covered by the floating nav.

I guess I could try linking to the tweet above it, but then how would I even get that ID... seems like a hack. What do you think is the best solution?

I was thinking more about the inline tweet display and I think it would be a good idea. That way the site is totally self-contained. Because although I cited minimalism and verisimilitude as defenses for its current layout, I really void my own principles by encouraging users to click on the tweet links. Then they're taken away from the page, perhaps never to return...

How are you man? Any sexy repos you've been working on?

**Comment by ashlinaronin** [comment]
(didn't merge yet because of the display issue)

**Comment by ashlinaronin** [comment]
Also, do you have any other ideas for making this better?

**Comment by tobobo** [comment]
Yeah maybe having a modal thing that shows the embedded tweet would be better, as it's not great that the second navbar overlaps the tweet.

I've been doing well! I'm all corporate now so most of the repos I'm working on are private ones on http://github.com/change

Although I did just report a bug to a javascript code style checker yesterday... that felt kinda sexy

**Comment by ashlinaronin** [comment]
I remember you talking about the upcoming merger when I was down in CA. Is your day-to-day different under corporate leadership? More strict coding style guides or anything?

I'll get to the modal thing soon, though it may be a little late as Mr. T descends in the rankings...

Another thing-- I'm starting to work on a portfolio site. What do you think is the best hosting service to use for something like that? Obviously it's not all static stuff. Paid heroku?

Deuces!

**Comment by tobobo** [comment]
Heroku would be fine, although it definitely isn't the cheapest option (though it's like $7/month, right? not bad).

You could also try creating your own heroku on something like digitalocean or atlantic.net, which is something I've been meaning to try. If you search for "roll your own heroku" or "diy heroku" there are a few good looking options out there.

Style is a little stricter, but it's mostly just the review process with other engineers that I'm getting used to—stuff like reading through other people's code and trying to identify potential bugs.

**Pull request merged**
